# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Stuff\SideWorks\VirtualTelecomLab\instruments\otdr.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OTDR(object):
    def setupUi(self, OTDR):
        OTDR.setObjectName("OTDR")
        OTDR.resize(926, 537)
        self.gridLayout = QtWidgets.QGridLayout(OTDR)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startBut = QtWidgets.QPushButton(OTDR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBut.sizePolicy().hasHeightForWidth())
        self.startBut.setSizePolicy(sizePolicy)
        self.startBut.setMinimumSize(QtCore.QSize(0, 0))
        self.startBut.setMaximumSize(QtCore.QSize(72, 16777215))
        self.startBut.setObjectName("startBut")
        self.horizontalLayout_2.addWidget(self.startBut)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(OTDR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(128, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.fibernSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fibernSpin.setMaximumSize(QtCore.QSize(128, 16777215))
        self.fibernSpin.setKeyboardTracking(False)
        self.fibernSpin.setDecimals(2)
        self.fibernSpin.setMinimum(1.0)
        self.fibernSpin.setMaximum(4.0)
        self.fibernSpin.setSingleStep(0.1)
        self.fibernSpin.setProperty("value", 1.45)
        self.fibernSpin.setObjectName("fibernSpin")
        self.verticalLayout_7.addWidget(self.fibernSpin)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(128, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.pwSpin = QtWidgets.QSpinBox(self.groupBox)
        self.pwSpin.setMaximumSize(QtCore.QSize(128, 16777215))
        self.pwSpin.setKeyboardTracking(False)
        self.pwSpin.setMinimum(1)
        self.pwSpin.setMaximum(1000)
        self.pwSpin.setSingleStep(1)
        self.pwSpin.setProperty("value", 100)
        self.pwSpin.setObjectName("pwSpin")
        self.verticalLayout_10.addWidget(self.pwSpin)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 4, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(128, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.pwrSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pwrSpin.setMaximumSize(QtCore.QSize(128, 16777215))
        self.pwrSpin.setKeyboardTracking(False)
        self.pwrSpin.setDecimals(2)
        self.pwrSpin.setMinimum(-10.0)
        self.pwrSpin.setMaximum(20.0)
        self.pwrSpin.setProperty("value", 0.0)
        self.pwrSpin.setObjectName("pwrSpin")
        self.verticalLayout_8.addWidget(self.pwrSpin)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(128, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.stopSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.stopSpin.setMaximumSize(QtCore.QSize(128, 16777215))
        self.stopSpin.setKeyboardTracking(False)
        self.stopSpin.setDecimals(2)
        self.stopSpin.setMinimum(0.1)
        self.stopSpin.setMaximum(1000.0)
        self.stopSpin.setProperty("value", 100.0)
        self.stopSpin.setObjectName("stopSpin")
        self.verticalLayout_11.addWidget(self.stopSpin)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 5, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.saveBut = QtWidgets.QPushButton(OTDR)
        self.saveBut.setMaximumSize(QtCore.QSize(2560, 16777215))
        self.saveBut.setObjectName("saveBut")
        self.verticalLayout_9.addWidget(self.saveBut)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.graphHolder = QtWidgets.QGridLayout()
        self.graphHolder.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.graphHolder.setObjectName("graphHolder")
        self.horizontalLayout.addLayout(self.graphHolder)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(OTDR)
        QtCore.QMetaObject.connectSlotsByName(OTDR)

    def retranslateUi(self, OTDR):
        _translate = QtCore.QCoreApplication.translate
        OTDR.setWindowTitle(_translate("OTDR", "OTDR - Virtual Telecom Lab"))
        self.startBut.setText(_translate("OTDR", "Run"))
        self.groupBox.setTitle(_translate("OTDR", "Controls"))
        self.label.setText(_translate("OTDR", "Fiber n"))
        self.label_3.setText(_translate("OTDR", "Pulse width (ns)"))
        self.label_2.setText(_translate("OTDR", "Power (dBm)"))
        self.label_4.setText(_translate("OTDR", "Stop Length (km)"))
        self.saveBut.setText(_translate("OTDR", "Save"))
