# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Stuff\SideWorks\VirtualTelecomLab\instruments\prbs_gen.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PRBSGenerator(object):
    def setupUi(self, PRBSGenerator):
        PRBSGenerator.setObjectName("PRBSGenerator")
        PRBSGenerator.resize(533, 188)
        self.gridLayout = QtWidgets.QGridLayout(PRBSGenerator)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(PRBSGenerator)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.f1ghzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1ghzCheck.setObjectName("f1ghzCheck")
        self.gridLayout_2.addWidget(self.f1ghzCheck, 3, 0, 1, 1)
        self.f1mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1mhzCheck.setChecked(True)
        self.f1mhzCheck.setObjectName("f1mhzCheck")
        self.gridLayout_2.addWidget(self.f1mhzCheck, 0, 0, 1, 1)
        self.fmultDial = QtWidgets.QDial(self.groupBox)
        self.fmultDial.setMinimum(10)
        self.fmultDial.setMaximum(1000)
        self.fmultDial.setSingleStep(10)
        self.fmultDial.setPageStep(100)
        self.fmultDial.setProperty("value", 100)
        self.fmultDial.setNotchTarget(10.0)
        self.fmultDial.setNotchesVisible(True)
        self.fmultDial.setObjectName("fmultDial")
        self.gridLayout_2.addWidget(self.fmultDial, 1, 1, 1, 1)
        self.f100mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f100mhzCheck.setChecked(False)
        self.f100mhzCheck.setObjectName("f100mhzCheck")
        self.gridLayout_2.addWidget(self.f100mhzCheck, 1, 0, 1, 1)
        self.fmultSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fmultSpin.setKeyboardTracking(False)
        self.fmultSpin.setDecimals(1)
        self.fmultSpin.setMinimum(0.1)
        self.fmultSpin.setMaximum(10.0)
        self.fmultSpin.setProperty("value", 1.0)
        self.fmultSpin.setObjectName("fmultSpin")
        self.gridLayout_2.addWidget(self.fmultSpin, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(PRBSGenerator)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.a100mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a100mvCheck.setObjectName("a100mvCheck")
        self.gridLayout_3.addWidget(self.a100mvCheck, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.offsetSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.offsetSpin.setKeyboardTracking(False)
        self.offsetSpin.setDecimals(1)
        self.offsetSpin.setMinimum(-100.0)
        self.offsetSpin.setMaximum(100.0)
        self.offsetSpin.setObjectName("offsetSpin")
        self.gridLayout_3.addWidget(self.offsetSpin, 3, 4, 1, 1)
        self.a10mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10mvCheck.setObjectName("a10mvCheck")
        self.gridLayout_3.addWidget(self.a10mvCheck, 2, 0, 1, 1)
        self.offsetSlider = QtWidgets.QSlider(self.groupBox_2)
        self.offsetSlider.setMinimum(-1000)
        self.offsetSlider.setMaximum(1000)
        self.offsetSlider.setOrientation(QtCore.Qt.Vertical)
        self.offsetSlider.setInvertedAppearance(False)
        self.offsetSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.offsetSlider.setTickInterval(100)
        self.offsetSlider.setObjectName("offsetSlider")
        self.gridLayout_3.addWidget(self.offsetSlider, 2, 4, 1, 1)
        self.a1vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1vCheck.setChecked(True)
        self.a1vCheck.setObjectName("a1vCheck")
        self.gridLayout_3.addWidget(self.a1vCheck, 0, 1, 1, 1)
        self.amultDial = QtWidgets.QDial(self.groupBox_2)
        self.amultDial.setMinimum(10)
        self.amultDial.setMaximum(100)
        self.amultDial.setSingleStep(1)
        self.amultDial.setPageStep(10)
        self.amultDial.setNotchTarget(10.0)
        self.amultDial.setNotchesVisible(True)
        self.amultDial.setObjectName("amultDial")
        self.gridLayout_3.addWidget(self.amultDial, 2, 2, 1, 1)
        self.amultSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.amultSpin.setKeyboardTracking(False)
        self.amultSpin.setDecimals(1)
        self.amultSpin.setMinimum(0.1)
        self.amultSpin.setMaximum(10.0)
        self.amultSpin.setProperty("value", 1.0)
        self.amultSpin.setObjectName("amultSpin")
        self.gridLayout_3.addWidget(self.amultSpin, 3, 2, 1, 1)
        self.a1mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1mvCheck.setObjectName("a1mvCheck")
        self.gridLayout_3.addWidget(self.a1mvCheck, 0, 0, 1, 1)
        self.a10vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10vCheck.setObjectName("a10vCheck")
        self.gridLayout_3.addWidget(self.a10vCheck, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(PRBSGenerator)
        QtCore.QMetaObject.connectSlotsByName(PRBSGenerator)

    def retranslateUi(self, PRBSGenerator):
        _translate = QtCore.QCoreApplication.translate
        PRBSGenerator.setWindowTitle(_translate("PRBSGenerator", "PRBS Generator (NRZ)- Virtual Telecom Lab"))
        self.groupBox.setTitle(_translate("PRBSGenerator", "Baud rate control"))
        self.f1ghzCheck.setText(_translate("PRBSGenerator", "1 Gbps"))
        self.f1mhzCheck.setText(_translate("PRBSGenerator", "1 Mbps"))
        self.f100mhzCheck.setText(_translate("PRBSGenerator", "100 Mbps"))
        self.label.setText(_translate("PRBSGenerator", "Multiplier"))
        self.groupBox_2.setTitle(_translate("PRBSGenerator", "Amplitude Control"))
        self.a100mvCheck.setText(_translate("PRBSGenerator", "100 mV"))
        self.label_3.setText(_translate("PRBSGenerator", "Offset (V)"))
        self.a10mvCheck.setText(_translate("PRBSGenerator", "10 mV"))
        self.a1vCheck.setText(_translate("PRBSGenerator", "1 V"))
        self.a1mvCheck.setText(_translate("PRBSGenerator", "1 mV"))
        self.a10vCheck.setText(_translate("PRBSGenerator", "10 V"))
        self.label_2.setText(_translate("PRBSGenerator", "Multiplier"))
