# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Stuff\SideWorks\VirtualTelecomLab\instruments\qam_gen.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QAMGenerator(object):
    def setupUi(self, QAMGenerator):
        QAMGenerator.setObjectName("QAMGenerator")
        QAMGenerator.resize(638, 257)
        self.gridLayout = QtWidgets.QGridLayout(QAMGenerator)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(QAMGenerator)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.f1ghzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1ghzCheck.setObjectName("f1ghzCheck")
        self.gridLayout_2.addWidget(self.f1ghzCheck, 3, 0, 1, 1)
        self.f1mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1mhzCheck.setChecked(True)
        self.f1mhzCheck.setObjectName("f1mhzCheck")
        self.gridLayout_2.addWidget(self.f1mhzCheck, 0, 0, 1, 1)
        self.fmultDial = QtWidgets.QDial(self.groupBox)
        self.fmultDial.setMinimum(10)
        self.fmultDial.setMaximum(5000)
        self.fmultDial.setSingleStep(10)
        self.fmultDial.setPageStep(100)
        self.fmultDial.setProperty("value", 100)
        self.fmultDial.setNotchTarget(10.0)
        self.fmultDial.setNotchesVisible(True)
        self.fmultDial.setObjectName("fmultDial")
        self.gridLayout_2.addWidget(self.fmultDial, 1, 1, 1, 1)
        self.f100mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f100mhzCheck.setChecked(False)
        self.f100mhzCheck.setObjectName("f100mhzCheck")
        self.gridLayout_2.addWidget(self.f100mhzCheck, 1, 0, 1, 1)
        self.fmultSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fmultSpin.setKeyboardTracking(False)
        self.fmultSpin.setDecimals(1)
        self.fmultSpin.setMinimum(0.1)
        self.fmultSpin.setMaximum(50.0)
        self.fmultSpin.setProperty("value", 1.0)
        self.fmultSpin.setObjectName("fmultSpin")
        self.gridLayout_2.addWidget(self.fmultSpin, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(QAMGenerator)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.a100mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a100mvCheck.setObjectName("a100mvCheck")
        self.gridLayout_3.addWidget(self.a100mvCheck, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.offsetSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.offsetSpin.setKeyboardTracking(False)
        self.offsetSpin.setDecimals(1)
        self.offsetSpin.setMinimum(-100.0)
        self.offsetSpin.setMaximum(100.0)
        self.offsetSpin.setObjectName("offsetSpin")
        self.gridLayout_3.addWidget(self.offsetSpin, 3, 3, 1, 1)
        self.a1vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1vCheck.setChecked(True)
        self.a1vCheck.setObjectName("a1vCheck")
        self.gridLayout_3.addWidget(self.a1vCheck, 0, 1, 1, 1)
        self.amultSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.amultSpin.setKeyboardTracking(False)
        self.amultSpin.setDecimals(1)
        self.amultSpin.setMinimum(0.1)
        self.amultSpin.setMaximum(10.0)
        self.amultSpin.setProperty("value", 1.0)
        self.amultSpin.setObjectName("amultSpin")
        self.gridLayout_3.addWidget(self.amultSpin, 3, 2, 1, 1)
        self.a10mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10mvCheck.setObjectName("a10mvCheck")
        self.gridLayout_3.addWidget(self.a10mvCheck, 2, 0, 1, 1)
        self.amultDial = QtWidgets.QDial(self.groupBox_2)
        self.amultDial.setMinimum(10)
        self.amultDial.setMaximum(100)
        self.amultDial.setSingleStep(1)
        self.amultDial.setPageStep(10)
        self.amultDial.setNotchTarget(10.0)
        self.amultDial.setNotchesVisible(True)
        self.amultDial.setObjectName("amultDial")
        self.gridLayout_3.addWidget(self.amultDial, 2, 2, 1, 1)
        self.offsetSlider = QtWidgets.QSlider(self.groupBox_2)
        self.offsetSlider.setMinimum(-1000)
        self.offsetSlider.setMaximum(1000)
        self.offsetSlider.setOrientation(QtCore.Qt.Vertical)
        self.offsetSlider.setInvertedAppearance(False)
        self.offsetSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.offsetSlider.setTickInterval(100)
        self.offsetSlider.setObjectName("offsetSlider")
        self.gridLayout_3.addWidget(self.offsetSlider, 2, 3, 1, 1)
        self.a10vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10vCheck.setObjectName("a10vCheck")
        self.gridLayout_3.addWidget(self.a10vCheck, 2, 1, 1, 1)
        self.a1mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1mvCheck.setObjectName("a1mvCheck")
        self.gridLayout_3.addWidget(self.a1mvCheck, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(QAMGenerator)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.phaseiSlider = QtWidgets.QSlider(self.groupBox_3)
        self.phaseiSlider.setMinimum(-1800)
        self.phaseiSlider.setMaximum(1800)
        self.phaseiSlider.setOrientation(QtCore.Qt.Horizontal)
        self.phaseiSlider.setObjectName("phaseiSlider")
        self.verticalLayout_2.addWidget(self.phaseiSlider)
        self.phaseiSpin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.phaseiSpin.setKeyboardTracking(False)
        self.phaseiSpin.setDecimals(1)
        self.phaseiSpin.setMinimum(-180.0)
        self.phaseiSpin.setMaximum(180.0)
        self.phaseiSpin.setObjectName("phaseiSpin")
        self.verticalLayout_2.addWidget(self.phaseiSpin)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.phaseqSlider = QtWidgets.QSlider(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseqSlider.sizePolicy().hasHeightForWidth())
        self.phaseqSlider.setSizePolicy(sizePolicy)
        self.phaseqSlider.setMinimum(-1800)
        self.phaseqSlider.setMaximum(1800)
        self.phaseqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.phaseqSlider.setObjectName("phaseqSlider")
        self.verticalLayout_2.addWidget(self.phaseqSlider)
        self.phaseqSpin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.phaseqSpin.setKeyboardTracking(False)
        self.phaseqSpin.setDecimals(1)
        self.phaseqSpin.setMinimum(-180.0)
        self.phaseqSpin.setMaximum(180.0)
        self.phaseqSpin.setObjectName("phaseqSpin")
        self.verticalLayout_2.addWidget(self.phaseqSpin)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.levelsSpin = QtWidgets.QSpinBox(self.groupBox_3)
        self.levelsSpin.setKeyboardTracking(False)
        self.levelsSpin.setMinimum(1)
        self.levelsSpin.setMaximum(16)
        self.levelsSpin.setSingleStep(1)
        self.levelsSpin.setProperty("value", 1)
        self.levelsSpin.setObjectName("levelsSpin")
        self.verticalLayout_2.addWidget(self.levelsSpin)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(QAMGenerator)
        QtCore.QMetaObject.connectSlotsByName(QAMGenerator)

    def retranslateUi(self, QAMGenerator):
        _translate = QtCore.QCoreApplication.translate
        QAMGenerator.setWindowTitle(_translate("QAMGenerator", "QAM Generator - Virtual Telecom Lab"))
        self.groupBox.setTitle(_translate("QAMGenerator", "Baud rate control"))
        self.f1ghzCheck.setText(_translate("QAMGenerator", "1 Gbps"))
        self.f1mhzCheck.setText(_translate("QAMGenerator", "1 Mbps"))
        self.f100mhzCheck.setText(_translate("QAMGenerator", "100 Mbps"))
        self.label.setText(_translate("QAMGenerator", "Multiplier"))
        self.groupBox_2.setTitle(_translate("QAMGenerator", "Amplitude Control"))
        self.a100mvCheck.setText(_translate("QAMGenerator", "100 mV"))
        self.label_3.setText(_translate("QAMGenerator", "Offset (V)"))
        self.a1vCheck.setText(_translate("QAMGenerator", "1 V"))
        self.a10mvCheck.setText(_translate("QAMGenerator", "10 mV"))
        self.a10vCheck.setText(_translate("QAMGenerator", "10 V"))
        self.a1mvCheck.setText(_translate("QAMGenerator", "1 mV"))
        self.label_2.setText(_translate("QAMGenerator", "Multiplier"))
        self.groupBox_3.setTitle(_translate("QAMGenerator", "Modulation Options"))
        self.label_5.setText(_translate("QAMGenerator", "Phase I"))
        self.label_6.setText(_translate("QAMGenerator", "Phase Q"))
        self.label_4.setText(_translate("QAMGenerator", "Bit levels"))
