# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Stuff\SideWorks\VirtualTelecomLab\instruments\signal_gen.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignalGenerator(object):
    def setupUi(self, SignalGenerator):
        SignalGenerator.setObjectName("SignalGenerator")
        SignalGenerator.resize(743, 314)
        self.gridLayout = QtWidgets.QGridLayout(SignalGenerator)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(SignalGenerator)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fmultDial = QtWidgets.QDial(self.groupBox)
        self.fmultDial.setMinimum(10)
        self.fmultDial.setMaximum(1000)
        self.fmultDial.setSingleStep(1)
        self.fmultDial.setPageStep(10)
        self.fmultDial.setProperty("value", 100)
        self.fmultDial.setNotchTarget(100.0)
        self.fmultDial.setNotchesVisible(True)
        self.fmultDial.setObjectName("fmultDial")
        self.gridLayout_2.addWidget(self.fmultDial, 3, 2, 1, 1)
        self.f1ghzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1ghzCheck.setObjectName("f1ghzCheck")
        self.gridLayout_2.addWidget(self.f1ghzCheck, 5, 1, 1, 1)
        self.f1hzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1hzCheck.setObjectName("f1hzCheck")
        self.gridLayout_2.addWidget(self.f1hzCheck, 0, 0, 1, 1)
        self.f100mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f100mhzCheck.setChecked(False)
        self.f100mhzCheck.setObjectName("f100mhzCheck")
        self.gridLayout_2.addWidget(self.f100mhzCheck, 3, 1, 1, 1)
        self.f100hzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f100hzCheck.setObjectName("f100hzCheck")
        self.gridLayout_2.addWidget(self.f100hzCheck, 3, 0, 1, 1)
        self.f1mhzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f1mhzCheck.setChecked(True)
        self.f1mhzCheck.setObjectName("f1mhzCheck")
        self.gridLayout_2.addWidget(self.f1mhzCheck, 0, 1, 1, 1)
        self.f10khzCheck = QtWidgets.QRadioButton(self.groupBox)
        self.f10khzCheck.setObjectName("f10khzCheck")
        self.gridLayout_2.addWidget(self.f10khzCheck, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.fmultSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fmultSpin.setKeyboardTracking(False)
        self.fmultSpin.setDecimals(2)
        self.fmultSpin.setMinimum(0.1)
        self.fmultSpin.setMaximum(10.0)
        self.fmultSpin.setSingleStep(0.01)
        self.fmultSpin.setProperty("value", 1.0)
        self.fmultSpin.setObjectName("fmultSpin")
        self.gridLayout_2.addWidget(self.fmultSpin, 5, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(SignalGenerator)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.chirpvarSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.chirpvarSpin.setKeyboardTracking(False)
        self.chirpvarSpin.setDecimals(2)
        self.chirpvarSpin.setMinimum(0.01)
        self.chirpvarSpin.setMaximum(100.0)
        self.chirpvarSpin.setObjectName("chirpvarSpin")
        self.verticalLayout.addWidget(self.chirpvarSpin)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.chirptSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.chirptSpin.setKeyboardTracking(False)
        self.chirptSpin.setMinimum(0.01)
        self.chirptSpin.setMaximum(100.0)
        self.chirptSpin.setProperty("value", 1.0)
        self.chirptSpin.setObjectName("chirptSpin")
        self.verticalLayout_2.addWidget(self.chirptSpin)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.chirpCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.chirpCheck.setObjectName("chirpCheck")
        self.gridLayout_5.addWidget(self.chirpCheck, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(SignalGenerator)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.offsetSlider = QtWidgets.QSlider(self.groupBox_2)
        self.offsetSlider.setMinimum(-100000)
        self.offsetSlider.setMaximum(100000)
        self.offsetSlider.setSingleStep(10)
        self.offsetSlider.setPageStep(100)
        self.offsetSlider.setOrientation(QtCore.Qt.Vertical)
        self.offsetSlider.setInvertedAppearance(False)
        self.offsetSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.offsetSlider.setTickInterval(10000)
        self.offsetSlider.setObjectName("offsetSlider")
        self.gridLayout_3.addWidget(self.offsetSlider, 2, 4, 1, 1)
        self.offsetSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.offsetSpin.setKeyboardTracking(False)
        self.offsetSpin.setDecimals(3)
        self.offsetSpin.setMinimum(-100.0)
        self.offsetSpin.setMaximum(100.0)
        self.offsetSpin.setSingleStep(0.01)
        self.offsetSpin.setObjectName("offsetSpin")
        self.gridLayout_3.addWidget(self.offsetSpin, 3, 4, 1, 1)
        self.a100mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a100mvCheck.setObjectName("a100mvCheck")
        self.gridLayout_3.addWidget(self.a100mvCheck, 3, 0, 1, 1)
        self.a10mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10mvCheck.setObjectName("a10mvCheck")
        self.gridLayout_3.addWidget(self.a10mvCheck, 2, 0, 1, 1)
        self.amultSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.amultSpin.setKeyboardTracking(False)
        self.amultSpin.setDecimals(2)
        self.amultSpin.setMinimum(0.1)
        self.amultSpin.setMaximum(10.0)
        self.amultSpin.setSingleStep(0.01)
        self.amultSpin.setProperty("value", 1.0)
        self.amultSpin.setObjectName("amultSpin")
        self.gridLayout_3.addWidget(self.amultSpin, 3, 2, 1, 1)
        self.amultDial = QtWidgets.QDial(self.groupBox_2)
        self.amultDial.setMinimum(10)
        self.amultDial.setMaximum(1000)
        self.amultDial.setSingleStep(1)
        self.amultDial.setPageStep(10)
        self.amultDial.setProperty("value", 100)
        self.amultDial.setNotchTarget(100.0)
        self.amultDial.setNotchesVisible(True)
        self.amultDial.setObjectName("amultDial")
        self.gridLayout_3.addWidget(self.amultDial, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 3, 1, 1)
        self.a1vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1vCheck.setChecked(True)
        self.a1vCheck.setObjectName("a1vCheck")
        self.gridLayout_3.addWidget(self.a1vCheck, 0, 1, 1, 1)
        self.a10vCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a10vCheck.setObjectName("a10vCheck")
        self.gridLayout_3.addWidget(self.a10vCheck, 2, 1, 1, 1)
        self.a1mvCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.a1mvCheck.setObjectName("a1mvCheck")
        self.gridLayout_3.addWidget(self.a1mvCheck, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(SignalGenerator)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dutySlider = QtWidgets.QSlider(self.groupBox_3)
        self.dutySlider.setMinimum(0)
        self.dutySlider.setMaximum(10000)
        self.dutySlider.setSingleStep(100)
        self.dutySlider.setPageStep(1000)
        self.dutySlider.setProperty("value", 5000)
        self.dutySlider.setOrientation(QtCore.Qt.Horizontal)
        self.dutySlider.setObjectName("dutySlider")
        self.gridLayout_4.addWidget(self.dutySlider, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 4, 1, 1)
        self.sawCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.sawCheck.setObjectName("sawCheck")
        self.gridLayout_4.addWidget(self.sawCheck, 0, 2, 1, 1)
        self.squareCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.squareCheck.setObjectName("squareCheck")
        self.gridLayout_4.addWidget(self.squareCheck, 2, 1, 1, 1)
        self.rsawCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.rsawCheck.setObjectName("rsawCheck")
        self.gridLayout_4.addWidget(self.rsawCheck, 1, 2, 1, 1)
        self.pulseCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.pulseCheck.setObjectName("pulseCheck")
        self.gridLayout_4.addWidget(self.pulseCheck, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 5, 1, 1)
        self.dutySpin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.dutySpin.setKeyboardTracking(False)
        self.dutySpin.setDecimals(2)
        self.dutySpin.setMaximum(100.0)
        self.dutySpin.setProperty("value", 50.0)
        self.dutySpin.setObjectName("dutySpin")
        self.gridLayout_4.addWidget(self.dutySpin, 2, 4, 1, 1)
        self.triangleCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.triangleCheck.setObjectName("triangleCheck")
        self.gridLayout_4.addWidget(self.triangleCheck, 1, 1, 1, 1)
        self.sineCheck = QtWidgets.QRadioButton(self.groupBox_3)
        self.sineCheck.setChecked(True)
        self.sineCheck.setObjectName("sineCheck")
        self.gridLayout_4.addWidget(self.sineCheck, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 6, 1, 1)
        self.phaseSlider = QtWidgets.QSlider(self.groupBox_3)
        self.phaseSlider.setMinimum(-18000)
        self.phaseSlider.setMaximum(18000)
        self.phaseSlider.setSingleStep(10)
        self.phaseSlider.setPageStep(100)
        self.phaseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.phaseSlider.setObjectName("phaseSlider")
        self.gridLayout_4.addWidget(self.phaseSlider, 1, 6, 1, 1)
        self.phaseSpin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.phaseSpin.setDecimals(2)
        self.phaseSpin.setMinimum(-180.0)
        self.phaseSpin.setMaximum(180.0)
        self.phaseSpin.setObjectName("phaseSpin")
        self.gridLayout_4.addWidget(self.phaseSpin, 2, 6, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.onoffBut = QtWidgets.QPushButton(SignalGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onoffBut.sizePolicy().hasHeightForWidth())
        self.onoffBut.setSizePolicy(sizePolicy)
        self.onoffBut.setObjectName("onoffBut")
        self.horizontalLayout_2.addWidget(self.onoffBut)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(SignalGenerator)
        QtCore.QMetaObject.connectSlotsByName(SignalGenerator)

    def retranslateUi(self, SignalGenerator):
        _translate = QtCore.QCoreApplication.translate
        SignalGenerator.setWindowTitle(_translate("SignalGenerator", "Signal Generator - Virtual Telecom Lab"))
        self.groupBox.setTitle(_translate("SignalGenerator", "Frequency Control"))
        self.f1ghzCheck.setText(_translate("SignalGenerator", "1 GHz"))
        self.f1hzCheck.setText(_translate("SignalGenerator", "1 Hz"))
        self.f100mhzCheck.setText(_translate("SignalGenerator", "100 MHz"))
        self.f100hzCheck.setText(_translate("SignalGenerator", "100 Hz"))
        self.f1mhzCheck.setText(_translate("SignalGenerator", "1 MHz"))
        self.f10khzCheck.setText(_translate("SignalGenerator", "10 KHz"))
        self.label.setText(_translate("SignalGenerator", "Multiplier"))
        self.groupBox_4.setTitle(_translate("SignalGenerator", "Chirp"))
        self.label_7.setText(_translate("SignalGenerator", "Variation (%)"))
        self.label_6.setText(_translate("SignalGenerator", "Period (s)"))
        self.chirpCheck.setText(_translate("SignalGenerator", "Enabled"))
        self.groupBox_2.setTitle(_translate("SignalGenerator", "Amplitude Control"))
        self.a100mvCheck.setText(_translate("SignalGenerator", "100 mV"))
        self.a10mvCheck.setText(_translate("SignalGenerator", "10 mV"))
        self.a1vCheck.setText(_translate("SignalGenerator", "1 V"))
        self.a10vCheck.setText(_translate("SignalGenerator", "10 V"))
        self.a1mvCheck.setText(_translate("SignalGenerator", "1 mV"))
        self.label_2.setText(_translate("SignalGenerator", "Multiplier"))
        self.label_3.setText(_translate("SignalGenerator", "Offset (V)"))
        self.groupBox_3.setTitle(_translate("SignalGenerator", "Wave Control"))
        self.label_4.setText(_translate("SignalGenerator", "Duty Cycle (%)"))
        self.sawCheck.setText(_translate("SignalGenerator", "Saw"))
        self.squareCheck.setText(_translate("SignalGenerator", "Square"))
        self.rsawCheck.setText(_translate("SignalGenerator", "Rev. Saw"))
        self.pulseCheck.setText(_translate("SignalGenerator", "Pulse"))
        self.triangleCheck.setText(_translate("SignalGenerator", "Triangle"))
        self.sineCheck.setText(_translate("SignalGenerator", "Sine"))
        self.label_5.setText(_translate("SignalGenerator", "Phase"))
        self.onoffBut.setText(_translate("SignalGenerator", "Output is OFF"))
